documentclass[12pt,a4paper]{article}
\usepackage{/home/mib-cri/local/lib64/R/share/texmf/Sweave}


\usepackage{indentfirst}

\usepackage{fullpage}
\usepackage{hyperref}
\usepackage{color}
\usepackage{times}
\usepackage{ifthen}
\SweaveOpts{echo=FALSE,results=hide,include=FALSE}



<<setUpTitle>>=
### Enter your name, e-mail and the project title below, or it will try and guess
### REMEMBER LaTeX does not like underscores _ in text, so escape then e.g. title="10660902\_FarrinerT\_PL\_GFOL"
#you can also add a .plan file if your finger file does not have your name in
title = ""
name = ""
email = ""
## If above are empty it will try and guess
if (nchar(title)==0){
title <- basename(getwd())
title <- gsub("_"," ",title)}
if (nchar(name)==0){
name <- system("finger $(whoami) |perl -ne 'print \"$1\n\" if m/Name: (.*)/;'",intern=TRUE)}
name <- name[length(name)]
if (nchar(email)==0){
email <- paste(sub(" ",".",name),"@cancer.org.uk",sep="")}
@

\begin{document}
\title{\Sexpr{title}}
\author{\Sexpr{name}\\
\small{Cancer Resarch UK - Cambridge Research Institute - Bioinformatics Core}\\
\texttt{\Sexpr{email}}}
\date{Report Generated \today}
\maketitle

\section{Table of Contents}
\tableofcontents

<<loadLibraries>>=
#Set cairo to be default graphics type for cluster use
options(bitmapType="cairo")
library(RColorBrewer)
library(hwriter)
library(xtable)
library(gplots)
library(WGCNA)
library(beadarray)
library(amap)




# The following setting is important, do not omit.
options(stringsAsFactors = FALSE);

@


\section{Introduction}

\subsection{Description}

ChIP-sequencing tecnologies combine massively parralell DNA sequencing and chromatin immunoprecipitation to identify protein/DNA interactions and epigenetic states..


\noindent
\vspace{5 mm}

\section{Quality Assessment and Genomic Distributions Of Reads}

\noindent
This report provides a summary of quality assessment for

@
\begin{figure}[h]
\begin{center}
\includegraphics[]{ReadsPlot.png}
\caption{Log2 of Number Base Pairs at Differing Read Depths}
\label{fig:ReadsPlot}
\end{center}
\end{figure}



\vspace{5 mm}

\begin{figure}[h]
\begin{center}
\includegraphics[]{CoveragePlot.png}
\caption{Log2 of Number Base Pairs at Differing Read Depths}
\label{fig:DepthPlot}
\end{center}
\end{figure}

\vspace{5 mm}

@
if(file.exists(Dispersion.png)){
\begin{figure}[h]
\begin{center}
\includegraphics[]{Dispersion.png}
\caption{Log2 of Number Base Pairs at Differing Read Depths}
\label{fig:DepthPlot}
\end{center}
\end{figure}


@
}

\end{document}
